version: 2

models:
  - name: my_model
    description: "This is a sample dbt model that transforms raw data."
    columns:
      - name: id
        description: "Primary key for the model"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the entity"
      - name: created_at
        description: "Timestamp of when the record was created"
        tests:
          - not_null
